image: Ubuntu1804 #образ для сборки
stack: node 12 #окружение
branches:
  only: 
    - main #ветка в git
cache: node_modules #кеширование
install: 
  - npm install
  - ps: $env:npm_config_loglevel = "verbose"; npm ci
build: off
test_script:
  - npm run lint && npm test