image: Ubuntu1804 #образ для сборки
branches:
  only: 
    - main #ветка в git
cache: node_modules #кеширование
environment:
  matrix:
    - node_version: "18"

install:
  # 1. Ставим git
  - sudo apt-get update && sudo apt-get install -y git

  # 2. Ставим nvm + Node
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"; nvm install "$env:node_version" || nvm install 18

  # 3. Проверка и установка зависимостей
  - node -v
  - npm -v
  - npm ci --verbose

build: off

test_script:
  - npm run test:ci